environment:
  matrix:

# Julia 0.6
  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x86/0.6/julia-0.6-latest-win32.exe"
    PYTHONDIR: "C:\\Python27"
    PYTHON: "C:\\Python27\\python.exe"

  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x86/0.6/julia-0.6-latest-win32.exe"
    PYTHONDIR: "C:\\Python33"
    PYTHON: "C:\\Python33\\python.exe"

  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x86/0.6/julia-0.6-latest-win32.exe"
    PYTHONDIR: "C:\\Python34"
    PYTHON: "C:\\Python34\\python.exe"

  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x86/0.6/julia-0.6-latest-win32.exe"
    PYTHONDIR: "use_conda"
    PYTHON: "Conda"

  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x64/0.6/julia-0.6-latest-win64.exe"
    PYTHONDIR: "C:\\Python27-x64"
    PYTHON: "C:\\Python27-x64\\python.exe"

  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x64/0.6/julia-0.6-latest-win64.exe"
    PYTHONDIR: "C:\\Python33-x64"
    PYTHON: "C:\\Python33-x64\\python.exe"

  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x64/0.6/julia-0.6-latest-win64.exe"
    PYTHONDIR: "C:\\Python34-x64"
    PYTHON: "C:\\Python34-x64\\python.exe"

  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x64/0.6/julia-0.6-latest-win64.exe"
    PYTHONDIR: "C:\\Python36-x64"
    PYTHON: "C:\\Python36-x64\\python.exe"

  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x64/0.6/julia-0.6-latest-win64.exe"
    PYTHONDIR: "use_conda"
    PYTHON: "Conda"

# Julia 0.7
  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x86/0.7/julia-0.7-latest-win32.exe"
    PYTHONDIR: "C:\\Python27"
    PYTHON: "C:\\Python27\\python.exe"

  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x86/0.7/julia-0.7-latest-win32.exe"
    PYTHONDIR: "C:\\Python33"
    PYTHON: "C:\\Python33\\python.exe"

  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x86/0.7/julia-0.7-latest-win32.exe"
    PYTHONDIR: "C:\\Python34"
    PYTHON: "C:\\Python34\\python.exe"

  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x86/0.7/julia-0.7-latest-win32.exe"
    PYTHONDIR: "use_conda"
    PYTHON: "Conda"

  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x64/0.7/julia-0.7-latest-win64.exe"
    PYTHONDIR: "C:\\Python27-x64"
    PYTHON: "C:\\Python27-x64\\python.exe"

  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x64/0.7/julia-0.7-latest-win64.exe"
    PYTHONDIR: "C:\\Python33-x64"
    PYTHON: "C:\\Python33-x64\\python.exe"

  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x64/0.7/julia-0.7-latest-win64.exe"
    PYTHONDIR: "C:\\Python34-x64"
    PYTHON: "C:\\Python34-x64\\python.exe"

  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x64/0.7/julia-0.7-latest-win64.exe"
    PYTHONDIR: "C:\\Python36-x64"
    PYTHON: "C:\\Python36-x64\\python.exe"

  - JULIA_URL: "https://julialang-s3.julialang.org/bin/winnt/x64/0.7/julia-0.7-latest-win64.exe"
    PYTHONDIR: "use_conda"
    PYTHON: "Conda"

# Nightlies
  - JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/winnt/x86/julia-latest-win32.exe"
    PYTHONDIR: "C:\\Python27"
    PYTHON: "C:\\Python27\\python.exe"

  - JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/winnt/x86/julia-latest-win32.exe"
    PYTHONDIR: "C:\\Python33"
    PYTHON: "C:\\Python33\\python.exe"

  - JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/winnt/x86/julia-latest-win32.exe"
    PYTHONDIR: "C:\\Python34"
    PYTHON: "C:\\Python34\\python.exe"

  - JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/winnt/x86/julia-latest-win32.exe"
    PYTHONDIR: "C:\\Python35"
    PYTHON: "C:\\Python35\\python.exe"

  - JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/winnt/x86/julia-latest-win32.exe"
    PYTHONDIR: "use_conda"
    PYTHON: "Conda"

  - JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/winnt/x64/julia-latest-win64.exe"
    PYTHONDIR: "C:\\Python27-x64"
    PYTHON: "C:\\Python27-x64\\python.exe"

  - JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/winnt/x64/julia-latest-win64.exe"
    PYTHONDIR: "C:\\Python33-x64"
    PYTHON: "C:\\Python33-x64\\python.exe"

  - JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/winnt/x64/julia-latest-win64.exe"
    PYTHONDIR: "C:\\Python34-x64"
    PYTHON: "C:\\Python34-x64\\python.exe"
    
  - JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/winnt/x64/julia-latest-win64.exe"
    PYTHONDIR: "C:\\Python35-x64"
    PYTHON: "C:\\Python35-x64\\python.exe"
    
  - JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/winnt/x64/julia-latest-win64.exe"
    PYTHONDIR: "C:\\Python37-x64"
    PYTHON: "C:\\Python37-x64\\python.exe"

  - JULIA_URL: "https://julialangnightlies-s3.julialang.org/bin/winnt/x64/julia-latest-win64.exe"
    PYTHONDIR: "use_conda"
    PYTHON: "Conda"

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12"
  - "SET PATH=%PYTHONDIR%;%PYTHONDIR%\\Scripts;%PATH%"
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile(
        $env:JULIA_URL,
        "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "versioninfo(); using Pkg;
      Pkg.add(pwd(), \"PyCall\"); Pkg.build(\"PyCall\")"

test_script:
  - C:\projects\julia\bin\julia --check-bounds=yes -e "Pkg.test(\"PyCall\")"
