name: Test with system Python

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
  workflow_dispatch:

jobs:
  test-system:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        architecture: [x64]
        python-version: ['3.x']
        julia-version:
          - '1'
          - 'nightly'
        include:
          # 32 bit Windows:
          - os: windows-latest
            architecture: x86
            python-version: '3.x'
            julia-version: '1'
          # Sweep python-version and julia-version only on Ubuntu:
          - os: ubuntu-latest
            architecture: x64
            python-version: '3.9'
            julia-version: '1'
          - os: ubuntu-latest
            architecture: x64
            python-version: '3.x'
            julia-version: '1.5'
          - os: ubuntu-latest
            architecture: x64
            python-version: '3.x'
            julia-version: '1.4'
          # Test Python 2.7 only with a few combinations (TODO: drop 2.7).
          # Note that it does not work in macOS:
          - os: ubuntu-latest
            architecture: x64
            python-version: '2.7'
            julia-version: '1'
          - os: windows-2019
            architecture: x64
            python-version: '2.7'
            julia-version: '1'
      fail-fast: false
    name: Test
      Julia ${{ matrix.julia-version }}
      Python ${{ matrix.python-version }}
      ${{ matrix.os }} ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - run: python -m pip install --user numpy
      - run: python -m pip install virtualenv
        # virtualenv test with Python 2.7 is failing for some reason.
        # Skipping it for now.
        if: ${{ matrix.python-version != '2.7' }}
      - run: virtualenv --version
        if: ${{ matrix.python-version != '2.7' }}
      - name: Install libpython2.7 for `find_libpython` test
        run: sudo apt-get install python2.7-dev
        if: ${{ matrix.python-version != '2.7' && matrix.os == 'ubuntu-latest' }}
      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.architecture }}
          show-versioninfo: true
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: python
      - run: julia test/check_deps_version.jl ${{ matrix.python-version }}
      - uses: julia-actions/julia-runtest@v1
        env:
          # Windows temp directories break the CI:
          #  https://github.com/actions/runner-images/issues/712
          #  so, we use
          #  https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context
          _TMP_DIR: ${{ runner.temp }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
